### ISSUE TITLE
Keepalived sysext overwrites Flatcar's `sbin/` symlink

### ISSUE THREAD

**Issue by tcldr** [flatcar/sysext-bakery#131]
## Description

Running the Keepalived sysext overwrites Flatcar's `/usr/sbin` symlink causing systemic failure.

Same issue as #105 

## Impact

Unable to boot a stable Flatcar instance with the Keepalived sysext installed.

## Environment and steps to reproduce

1. **Set-up**:
  - Create a minimal Flatcar instance with the following config:
  ```
  variant: flatcar
  version: 1.1.0
  
  storage:
    files:
      - path: /etc/extensions/keepalived.raw
         contents:
         source: https://extensions.flatcar.org/extensions/keepalived-v2.3.1-x86-64.raw 
  ```
3. **Task**:
    - Boot system (local via QEMU is fine)
5. **Action(s)**:
    - Boot system (local via QEMU is fine)
4. **Error**:
    - `[FAILED] Failed to start update-engine.service - Update Engine.`
    - `Update Strategy: No Reboot` displayed on console shell
    - Remote SSH connections dropped
    - etc.

## Expected behavior

Successful boot.

## Additional information

Please add any information here that does not fit the above format.
